intercom autoboot implemented -API_KEY
stackupfinance/stackup pull request #277
Opened 2022-02-20 06:51 UTC by arbob

2022-02-20 13:28 UTC, hazim-j requested changes
Left a few comments. What happens if no app id is given or if it's invalid? Would it just not show the intercom bubble?

2022-02-20 13:28 UTC, hazim-j commented on apps/web/pages/_app.js
> +import { App as API_KEYS } from '../src/config';
Let's just do:

```js
import { App } from '../src/config';
```

Keeps it consistent with everywhere else and easier to search for later.

2022-02-20 13:28 UTC, hazim-j commented on apps/web/pages/_app.js
> +    <IntercomProvider appId={INTERCOM_APP_ID} autoBoot={true}>
We can just put `App.intercom.apiKey` in `appId` prop. The indirection probably not required.

2022-02-20 13:28 UTC, hazim-j commented on apps/web/src/config/app.js
> +    apiKey: process.env.NEXT_PUBLIC_INTERCOM_API_KEY || '',
Is this called an `APP_ID` or an `API_KEY` according to intercom docs? If it's an app id we shoulc probably keep it consistent here to avoid confusion later.

Also, since it's a new environment variable can you add it to the env table in `apps/web/README.md`.

2022-02-20 13:28 UTC, hazim-j commented on apps/web/pages/_app.js
> +    <IntercomProvider appId={INTERCOM_APP_ID} autoBoot={true}>
Thoughts on `autoBoot={true}` vs just `autoBoot` since it's a boolean value?

2022-02-20 13:38 UTC, arbob commented on apps/web/pages/_app.js
> +import { App as API_KEYS } from '../src/config';
`import { App }` is conflicting with the `App` component, that's why had to use a pseudonym

2022-02-20 13:40 UTC, hazim-j commented on apps/web/pages/_app.js
> +import { App as API_KEYS } from '../src/config';
`import { App: { intercom } }` should work right?

2022-02-20 13:40 UTC, hazim-j commented on apps/web/pages/_app.js
> +import { App as API_KEYS } from '../src/config';
or `import { App as AppConfig }` would be better too imo.

2022-02-20 13:40 UTC, arbob commented on apps/web/pages/_app.js
> +    <IntercomProvider appId={INTERCOM_APP_ID} autoBoot={true}>
done.

2022-02-20 13:41 UTC, arbob commented on apps/web/src/config/app.js
> +    apiKey: process.env.NEXT_PUBLIC_INTERCOM_API_KEY || '',
Yes. It's `APP_ID`. Alright. will add it to the table

2022-02-20 13:42 UTC, arbob commented on apps/web/pages/_app.js
> +    <IntercomProvider appId={INTERCOM_APP_ID} autoBoot={true}>
that works too.

2022-02-20 13:55 UTC, arbob commented
We will need to test the intercom with a production AppID. Maybe @hazim-j can create an account and test it or send over the app_id to test?

2022-02-20 13:56 UTC, arbob commented
However, currently an incorrect APP_ID is being given so nothing pops up.

2022-02-20 14:03 UTC, hazim-j commented on apps/web/.env.example
> +NEXT_PUBLIC_INTERCOM_APP_ID=intercome-app-id
Can we add new line here.

(I'm very OCD with style lol)

2022-02-20 14:09 UTC, hazim-j commented
LGTM. Let me look into setting up the intercom account and we can test it before merge.

2022-02-22 16:40 UTC, hazim-j requested changes

2022-02-22 16:45 UTC, hazim-j requested changes

2022-02-22 16:45 UTC, hazim-j commented on apps/web/pages/home.js
> +      window.Intercom('boot', {
Can we use `boot` from `useIntercom` hook?

https://www.npmjs.com/package/react-use-intercom#useintercom

2022-02-22 16:45 UTC, hazim-j commented on apps/web/pages/home.js
> +        api_base: 'https://api-iam.intercom.io',
Probably add this to environment variable rather than hardcoding here?

2022-02-22 16:45 UTC, hazim-j commented on apps/web/pages/home.js
> +        created_at: Date.now(), // Signup date as a Unix timestamp
Can we get this from the user instead of `Date.now()`?

2022-02-25 21:17 UTC, hazim-j approved these changes

2022-02-25 21:23 UTC, merged