Secure password with KDF function, using username as salt
stackupfinance/stackup pull request #326
Opened 2022-03-03 18:35 UTC by jspruance

Increase password security by using a scrypt KDF to encode the password, using the username as the salt. This happens prior to AES encoding of the private key, using the KDF-encrypted password.

We are using the 'scrypt-js' lib for KDF:
https://github.com/ricmoo/scrypt-js

Since we are using the username for the salt in the KDF, many files needed to be updated to pass in the username to the 'initEncryptedIdentity', 'decryptSigner' and 'reencryptSigner' functions.

2022-03-03 19:05 UTC, hazim-j commented
> I did manual testing for:
> 
> 1) Create new account
> 
> 2) Add guardians
> 
> 3) Logout
> 
> 4) Login
> 
> 
> 
> What other flows should I test?

How about change password and recover account with guardian approval?

2022-03-03 19:22 UTC, hazim-j requested changes
Looking good! Just left some minor comments.

2022-03-03 19:22 UTC, hazim-j commented on apps/contracts/lib/wallet/proxy.js
> +    throw(error);
Probably just want to leave this to log and swallow the error. I found the aes decrypt function sometimes returns undefined or throws an error with incorrect password. By just logging it we make sure response from this function remains consistent.

2022-03-03 19:22 UTC, hazim-j commented on apps/web/pages/onboard/summary.js
> +    const ephemeralSigner = walletLib.proxy.decryptSigner(ephemeralWallet, data.password, user.username);
Do we need to await here?

2022-03-03 19:22 UTC, hazim-j commented on apps/web/src/state/recover.js
> +          const signer = wallet.proxy.decryptSigner({ encryptedSigner }, password, user.username);
await here as well?

2022-03-03 19:22 UTC, hazim-j commented on apps/web/src/state/recover.js
>          const { savedGuardianRequest } = get();
Deconstruct in same line?

2022-03-03 19:22 UTC, hazim-j commented on apps/web/src/state/recover.js
> +        const signer = wallet.proxy.decryptSigner(userWallet, password, user.username);
Another await?

2022-03-03 19:22 UTC, hazim-j commented on apps/web/src/state/wallet.js
> +        const signer = wallet.proxy.decryptSigner(userWallet, data.password, data.username);
Another one. Plus all the ones below as well.

2022-03-04 02:06 UTC, jspruance commented on apps/web/pages/onboard/summary.js
> +    const ephemeralSigner = walletLib.proxy.decryptSigner(ephemeralWallet, data.password, user.username);
yep, you're right since it called kdf which is await - updated.

2022-03-04 02:06 UTC, jspruance commented on apps/web/src/state/recover.js
> +          const signer = wallet.proxy.decryptSigner({ encryptedSigner }, password, user.username);
updated

2022-03-04 02:06 UTC, jspruance commented on apps/web/src/state/recover.js
>          const { savedGuardianRequest } = get();
combined - updated

2022-03-04 02:06 UTC, jspruance commented on apps/web/src/state/recover.js
> +        const signer = wallet.proxy.decryptSigner(userWallet, password, user.username);
added

2022-03-04 02:06 UTC, jspruance commented on apps/web/src/state/wallet.js
> +        const signer = wallet.proxy.decryptSigner(userWallet, data.password, data.username);
added + ones below. also did a search and found two other instances - all updated.

2022-03-05 06:55 UTC, jspruance commented
Adding a timestamp to the login signature. This is what I came up with:

1) the 'lookup' route on the server creates the timestamp and sends it back to the client along with the user info
2) The client uses the timestamp along with the existing message for signing
3) The backend maintains a map of usernames and timestamps to differentiate between different users / requests and deletes the map entry after each request.

2022-03-05 20:15 UTC, hazim-j commented
> Adding a timestamp to the login signature. This is what I came up with:
> 
> 1. the 'lookup' route on the server creates the timestamp and sends it back to the client along with the user info
> 2. The client uses the timestamp along with the existing message for signing
> 3. The backend maintains a map of usernames and timestamps to differentiate between different users / requests and deletes the map entry after each request.

I'm okay with this approach. Only thing we should consider is maintaining that map in the DB otherwise the server becomes stateful and we'll run into some issues when we have to increase the number of processes to more than 1.

Alternatively, did you experiment with any stateless solutions? One approach I can think off:
1 . Client sends timestamp + signature of timestamp
2. Server verifies timestamp is within a 5 second window
3. If yes then verify signature of timestamp is valid

2022-03-06 02:27 UTC, jspruance commented
> > Adding a timestamp to the login signature. This is what I came up with:
> > 
> > 1. the 'lookup' route on the server creates the timestamp and sends it back to the client along with the user info
> > 2. The client uses the timestamp along with the existing message for signing
> > 3. The backend maintains a map of usernames and timestamps to differentiate between different users / requests and deletes the map entry after each request.
> 
> I'm okay with this approach. Only thing we should consider is maintaining that map in the DB otherwise the server becomes stateful and we'll run into some issues when we have to increase the number of processes to more than 1.
> 
> Alternatively, did you experiment with any stateless solutions? One approach I can think off: 1 . Client sends timestamp + signature of timestamp 2. Server verifies timestamp is within a 5 second window 3. If yes then verify signature of timestamp is valid

Yes, maintaining the map is the biggest drawback to this approach. I was thinking about that stateless approach, but was hesitant because I thought that actually sending the timestamp from client to server might defeat the purpose (exposing it for interception, etc). But maybe I am overthinking it and it will still provide a benefit. I'll give it a try and we can see how we like it - thanks.

2022-03-06 04:12 UTC, hazim-j commented
From my understanding if it was intercepted and changed in anyway the signature would become invalid and authentication would fail. Unless you can think of a scenario I'm missing? The only gap I can think of would be to reduce the time window to as short a duration as possible.

2022-03-06 04:28 UTC, hazim-j commented on apps/backend/src/controllers/auth.controller.js
> +  const timestampExpired = (currentTime - timestamp > 300000) ? true : false;
Consider moving this logic into `authService` for readability?

`apps/backend/src/services/auth.service.js`
```js
module.exports.isTimestampExpired = (timestamp) => {
    // Check if timestamp is within 1 minute.
    return Date.now() - timestamp > 60000;
}
```

In this file:
```js
if (authService.isTimestampExpired(timestamp)) throw ...
```

2022-03-06 04:28 UTC, hazim-j commented on apps/backend/src/utils/web3.js
> +module.exports.recoverAddressFromLoginSignature = (signature, timestamp) => ethers.utils.verifyMessage(`${loginMessage}${timestamp}`, signature);
I wonder if `loginMessage` provides any additional benefit? Would it be easier and just as secure if we just signed the timestamp instead?

2022-03-07 21:02 UTC, jspruance commented on apps/backend/src/controllers/auth.controller.js
> +  const timestampExpired = (currentTime - timestamp > 300000) ? true : false;
That's a nice improvement...code updated.

2022-03-07 21:05 UTC, jspruance commented on apps/backend/src/utils/web3.js
> +module.exports.recoverAddressFromLoginSignature = (signature, timestamp) => ethers.utils.verifyMessage(`${loginMessage}${timestamp}`, signature);
I think it slightly increases security since knowledge of the timestamp and message would be needed. And the timestamp is readable in the request body but the message isn't so I like that additional protection. What do you think?

2022-03-07 22:48 UTC, hazim-j commented on apps/backend/src/utils/web3.js
> +module.exports.recoverAddressFromLoginSignature = (signature, timestamp) => ethers.utils.verifyMessage(`${loginMessage}${timestamp}`, signature);
Yeah true, however `loginMessage` is still hardcoded in the codebase and available client side too which makes it redundant from a security perspective. I guess there might be value in showing that this message was signed with the intent of being used to login to Stackup rather than signing an ambiguous timestamp that could be used anywhere.

Let's keep it but maybe consider changing the message to:
```js
`Welcome to Stackup!\nSign this message to log into your Stackup account.\nTimestamp: ${timestamp}`
```

This message is more aligned to what I've seen on other systems like Polygon wallet.

2022-03-08 16:43 UTC, jspruance commented on apps/backend/src/utils/web3.js
> +module.exports.recoverAddressFromLoginSignature = (signature, timestamp) => ethers.utils.verifyMessage(`${loginMessage}${timestamp}`, signature);
Sure, message updated.

2022-03-08 19:26 UTC, hazim-j requested changes
Approach is good. Just minor things for style and readability. Also missed added salt `apps/web/src/state/recover.js`

2022-03-08 19:26 UTC, hazim-j commented on apps/web/src/state/account.js
> +            timestamp: timestamp,
```js
signature: await signer.signMessage(`${loginMessage}${timestamp}`),
timestamp,
```

2022-03-08 19:26 UTC, hazim-j commented on apps/web/src/state/onboard.js
> +          set({ ephemeralWallet: ephemeralWallet });
```js
set({ ephemeralWallet });
```

2022-03-08 19:26 UTC, hazim-j commented on apps/web/src/state/recover.js
> +          const { encryptedSigner } = await wallet.proxy.initEncryptedIdentity(password);
Not passing username here

2022-03-08 19:26 UTC, hazim-j commented on apps/contracts/lib/wallet/proxy.js
> +module.exports.decryptSigner = async (wallet, password, username) => {
For all functions in this file, instead of naming the argument `username` should we name it `salt` instead? This module is only concerned with encrypting and decrypting and doesn't need to know what we use as salt.

2022-03-08 19:26 UTC, hazim-j commented on apps/web/src/state/account.js
> +import scrypt from 'scrypt-js';
unused import

2022-03-08 19:26 UTC, hazim-j commented on apps/web/src/state/account.js
> +              wallet: newWallet,
`newWallet` indirection not required. This should work.

```js
wallet: await walletLib.proxy.initEncryptedIdentity(data.password, data.username);
```

2022-03-08 19:26 UTC, hazim-j commented on apps/web/src/state/recover.js
>          if (!savedGuardianRequest) return;
This is where TS would be useful. Not sure if worth being this defensive, but:

```js
if (!savedGuardianRequest || !user) return;
```

2022-03-08 20:58 UTC, jspruance commented on apps/web/src/state/account.js
> +              wallet: newWallet,
sure, it's just my style to be a little more explicit, but can do this as well

2022-03-08 22:18 UTC, hazim-j commented on apps/web/src/state/account.js
> +              wallet: newWallet,
We can leave it if this is the style you prefer! I'm always shooting for the one-liner haha

2022-03-09 00:06 UTC, jspruance commented on apps/contracts/lib/wallet/proxy.js
> +    console.log(error.message);
Fixed

2022-03-09 00:07 UTC, jspruance commented on apps/contracts/lib/wallet/proxy.js
> +  }
Fixed

2022-03-09 00:12 UTC, jspruance commented on apps/web/package.json
> +    "scrypt-js": "^3.0.1",
Moved to contracts

2022-03-09 00:17 UTC, jspruance commented on apps/web/src/state/account.js
> +            timestamp: timestamp,
Code updated

2022-03-09 00:17 UTC, jspruance commented on apps/web/src/state/onboard.js
> +          set({ ephemeralWallet: ephemeralWallet });
Updated

2022-03-09 00:17 UTC, jspruance commented on apps/web/src/state/recover.js
> +          const { encryptedSigner } = await wallet.proxy.initEncryptedIdentity(password);
Added

2022-03-09 00:17 UTC, jspruance commented on apps/contracts/lib/wallet/proxy.js
> +module.exports.decryptSigner = async (wallet, password, username) => {
Agree...updated param name to 'salt'

2022-03-09 00:17 UTC, jspruance commented on apps/web/src/state/account.js
> +import scrypt from 'scrypt-js';
removed

2022-03-09 00:17 UTC, jspruance commented on apps/web/src/state/account.js
> +              wallet: newWallet,
updated

2022-03-09 00:18 UTC, jspruance commented on apps/web/src/state/recover.js
>          if (!savedGuardianRequest) return;
added

2022-03-09 03:55 UTC, hazim-j requested changes
Since this is a mono repo, there shouldn't be a `apps/contracts/package-lock.json` file. Make sure you added `scrypt-js` with the following command from the repo's root directory:

```bash
yarn workspace @stackupfinance/web remove scrypt-js
yarn workspace @stackupfinance/contracts add scrypt-js
```

Also, still need to fix the lint error here: https://github.com/stackupfinance/stackup/runs/5473197979?check_suite_focus=true#step:5:11

You can run `yarn lint:fix && yarn prettier` locally to check.

2022-03-10 09:52 UTC, hazim-j approved these changes

2022-03-10 09:53 UTC, merged