Session Replay
stackupfinance/stackup pull request #448
Opened 2022-04-10 04:50 UTC by arbob

Added session replay using OpenReplay with user context.

2022-04-12 03:22 UTC, hazim-j requested changes

2022-04-12 03:22 UTC, hazim-j commented on apps/web/src/utils/analytics.js
> +});
Let's not mix this with analytics since it's kinda separate from amplitude. Consider creating a custom hook under `apps/web/src/hooks/openReplay.js` and putting the integration there. And then in `_app.js` we can just call a `useOpenRelay()` hook.

2022-04-12 03:22 UTC, hazim-j commented on apps/web/pages/home.js
> +    openReplayTracker.setUserID(user.username);
This should be handled in a custom openReplay hook as well (see pusher hook for example).

2022-04-12 03:26 UTC, hazim-j commented on apps/web/src/utils/analytics.js
> +  // __DISABLE_SECURE_MODE: true, // enable this during development mode
Next JS should be able to tell us if we're in dev or prod right?

2022-04-12 06:37 UTC, arbob commented
> Also have you checked if open replay will sanitise data out of the box or is there an extra setup required? It's important we get that part right.

yes. i believe the sensitive things in our app are passwords and email. it hides it by default

2022-04-13 06:35 UTC, hazim-j requested changes

2022-04-13 06:35 UTC, hazim-j commented on apps/web/package.json
> -    "dev": "next dev -p 8080",
Let's not change ports in this PR.

2022-04-13 06:35 UTC, hazim-j commented on apps/web/package.json
> -    "start": "next start -p 8080",
Same here.

2022-04-13 06:35 UTC, hazim-j commented on apps/web/src/utils/openReplay.js
> +  __DISABLE_SECURE_MODE: process.env.NODE_ENV === 'production',
Disable secure mode in production? Do you mean `process.env.NODE_ENV !== 'production'`?

2022-04-13 06:35 UTC, hazim-j commented on apps/web/src/utils/openReplay.js
> +  onStart: ({ sessionID }) => console.log('OpenReplay tracker started with session: ', sessionID),
Probably not required to do this just for logs.

2022-04-13 06:35 UTC, hazim-j commented on apps/web/pages/home.js
> +    openReplayTracker.setUserID(user.username);
I can't see the change? The reason this should be done in a hook is because that's the only way you're going to be able to detect if user is authenticated or not.

You also can't do this in the home page because what if they're on a different page and decide to hard reload? OpenReplay won't be able to identify them.

Also a custom hook that's initiated in the _app.js file should only render once so it's not gonna break the tracker.

2022-04-13 06:37 UTC, hazim-j commented on apps/web/src/utils/analytics.js
> +});
See comment below. But you would initialise openReplay outside the custom hook and then update it accordingly depending on auth state.

2022-04-13 06:46 UTC, hazim-j commented
> > Also have you checked if open replay will sanitise data out of the box or is there an extra setup required? It's important we get that part right.
> 
> yes. i believe the sensitive things in our app are passwords and email. it hides it by default

Let's probably obscure all input data by default.

2022-04-13 10:20 UTC, arbob commented on apps/web/package.json
> -    "dev": "next dev -p 8080",
yeah sorry.  my mac has reserved port 8080 so i have to change it everytime i load new branch. fixed.

2022-04-13 10:28 UTC, arbob commented on apps/web/src/utils/analytics.js
> +});
ah yes. now i got it. i thought you were telling me to create a hook to initialize the constructor. 
i have moved the user identification for openreplay to useauth so that it will be attached to username only on auth.

2022-04-15 01:54 UTC, hazim-j commented
Closing this PR since we are moving away from web app.

2022-04-15 01:54 UTC, closed without merging