initial frontend monorepo setup
stackupfinance/stackup pull request #50
Opened 2021-10-31 06:10 UTC by nsolante

Setup for frontend mono, let me know if this is the direction you wanted to go or if the setup is fine

2021-11-01 03:22 UTC, hazim-j reviewed
Looks good! Is this all still boilerplate code from Next.js? Could we add prettier and also rename the workspace to `web` instead of `frontend`?

2021-11-01 03:25 UTC, nsolante commented
aight, will change from `frontend` to `web`. Yea still pretty much boilerplate code from next.js still on the other pages

2021-11-02 23:54 UTC, hazim-j requested changes
Looks good. Some small changes. I reckon let's add prettier to this and then merge. Can tackle the rest of the login flow in next PR.

You can see https://github.com/stackupfinance/checkout for prettier integration example.

2021-11-02 23:54 UTC, hazim-j commented on apps/web/.gitignore
> +.DS_Store
can we remove this.

2021-11-02 23:54 UTC, hazim-j commented on .gitignore
> +.idea
Can we remove this or move `.DS_Store` under a `#misc` section.

2021-11-02 23:59 UTC, hazim-j commented
You'll need to add a `yarn run prettier` command to the `web` package so that the `Code format` step in the monorepo workflow can pick it up.

2021-11-05 03:41 UTC, nsolante commented
aight ill do all of those changes

2021-11-09 10:47 UTC, hazim-j requested changes
You'll need two more files:

`.prettierrc.json`: This can just be a blank json for now.
`.eslintignore`: Look at the checkout repo for what you need.

Will need to also sort out `yarn.lock` merge conflict.

2021-11-09 10:47 UTC, hazim-j commented on apps/web/package.json
> +    "lint": "next lint",
can you also add a `lint:fix: "eslint . --fix"` command

2021-11-09 10:47 UTC, hazim-j commented on apps/web/.eslintrc.json
> +  "extends": "next/core-web-vitals"
You'll need to extend prettier config here.

```json
{
  "extends": ["next", "next/core-web-vitals", "prettier"]
}
```

2021-11-09 10:47 UTC, hazim-j commented on apps/web/.eslintrc.json
> +  "extends": "next/core-web-vitals"
For reference if you want to integrate prettier with es-lint: https://github.com/prettier/eslint-config-prettier

2021-11-12 02:19 UTC, hazim-j commented
Will be merged in https://github.com/stackupfinance/stackup/pull/67

2021-11-12 02:19 UTC, closed without merging