Feature/ramp
stackupfinance/stackup pull request #781
Opened 2022-07-01 19:00 UTC by jspruance

Adding Ramp Network integration code.

From UI: 
- Click 'Deposit' 
- 'Deposit with Ramp'
- Ramp UI opens

2022-07-02 02:57 UTC, hazim-j requested changes
You might need to rebase this branch with the latest main.

2022-07-02 02:57 UTC, hazim-j commented on apps/backup/tsconfig.json
> +    "allowJs": true,                          /* Allow javascript files to be compiled. */
Is this required?

2022-07-02 02:57 UTC, hazim-j commented on apps/backup/src/routes/v1/wallet.route.ts
> +});
Do we need a health check for ramp integration?

2022-07-02 02:57 UTC, hazim-j commented on apps/backup/package.json
> +    "dev": "set NODE_ENV=development && tsc-watch --onSuccess \"node ./build/index.js\"",
let's not commit this in this PR since it will break macOS/Linux environment.

2022-07-02 02:57 UTC, hazim-j commented on apps/mobile/android/build.gradle
> +        // maven { url 'https://jitpack.io' }
Removed the comment `// maven { url 'https://jitpack.io' }`

2022-07-02 02:57 UTC, hazim-j commented on apps/mobile/src/components/buyTokenItem.tsx
> +import React, {PropsWithChildren} from 'react';
Is this file still required?

2022-07-02 02:57 UTC, hazim-j commented on apps/mobile/src/components/sheets/buyTokenSheet.tsx
> +import React from 'react';
This one too?

2022-07-02 02:57 UTC, hazim-j commented on apps/mobile/src/components/sheets/depositSheet.tsx
> +  });
Couple things:

1. I'd move this logic to a hook
2. Can we lock certain fields? (`defaultAsset`, `fiatCurrency`, `userAddress`.

2022-07-02 02:57 UTC, hazim-j commented on apps/mobile/src/components/sheets/depositSheet.tsx
> +          onPress={() => ramp?.show()}
```ts
onPress={onDepositWithRamp}
```

```ts
const ramp = useRamp()
const onDepositWithRamp = () => {
   logEvent(...)
   ramp.show(...)
}
```

2022-07-02 02:57 UTC, hazim-j commented on apps/mobile/src/config/env.ts
> +  SENTRY_DSN: Config.STACKUP_MOBILE_SENTRY_DNS,
Remove this

2022-07-02 03:36 UTC, jspruance commented on apps/mobile/src/components/buyTokenItem.tsx
> +import React, {PropsWithChildren} from 'react';
Not strictly, but I thought we were going to come back to the more customized integration later - or should I just scrap it?

2022-07-07 13:34 UTC, hazim-j approved these changes

2022-07-07 13:35 UTC, merged