Search bar logo fix
stackupfinance/stackup pull request #94
Opened 2021-11-22 21:29 UTC by JohnRising

Search bar logo now takes user home instead of Stackup website.

2021-11-22 23:04 UTC, hazim-j requested changes

2021-11-22 23:04 UTC, hazim-j commented on apps/web/src/components/header.js
> +                maxH="32px"
nice catch!

2021-11-22 23:04 UTC, hazim-j commented on apps/web/src/components/search.js
> +            <LinkOverlay href="/home" target="_self">
You might want to use the `next/link` for navigating within the app in this situation. Have a look here for reference: https://chakra-ui.com/docs/navigation/link-overlay#usage-with-routing-library

You can also search up `NextLink` in the code base for examples.

2021-11-23 00:05 UTC, JohnRising commented on apps/web/src/components/search.js
> +            <LinkOverlay href="/home" target="_self">
Done per https://github.com/stackupfinance/stackup/pull/94/commits/2c686c6a499b8bc3c751688aabf69647d71bccfc

2021-11-23 00:10 UTC, hazim-j approved these changes
LGTM

2021-11-23 00:12 UTC, merged